batchsize: 128
epochs: 350

dataset:
  name: mnist

model:
  name: VGG16
  type: vgg
  encoder: ['C:1:64', 'B:64:64', 'B:64:64',
            'B:64:128', 'B:128:128', 'M',
            'B:128:256', 'B:256:256', 'B:256:256', 'M',
            'B:256:512', 'B:512:512', 'B:512:512', 'M', 'B:512:512', 'B:512:512', 'B:512:512', 'M']

optim:
  class: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4

scheduler:
  class: MultiStepLR
  milestones: [150, 250]
  gamma: 0.1