dataset:
  name: cifar-10
  train_len: 10000
  test_len: 500

model:
  name: typeg_autoencoder
  type: vgg16
  encoder: [3, 64, 128, 'M', 256, 256, 'M', 512, 512]
  decoder: [512, 512, 'U', 256, 256, 'U', 128, 64, 3]
  in_channels: 3
  z_channels: 16

epochs: 100
batchsize: 32
