batchsize: 128
epochs: 350

dataset:
  name: cifar-10

model:
  name: RESNET12FIX
  type: resnet-fixup
  stride: 2
  encoder: ['C:3:64', 'B:64:64', 'B:64:128', 'B:128:128', 'B:128:256',
            'B:256:256', 'B:256:512', 'B:512:512']

optim:
  class: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4

scheduler:
  class: MultiStepLR
  milestones: [150, 250]
  gamma: 0.1