batchsize: 128
epochs: 350

dataset:
  name: cifar-10-normed

model:
  name: RESNET12FIX
  type: resnet-fixup
  encoder: [3, 64, 64, 128, 128, 256, 256, 512, 512]

optim:
  class: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4

scheduler:
  class: MultiStepLR
  milestones: [150, 250]
  gamma: 0.1